version: '2'
services:
  example1:
    network_mode: host
    image: robocomp/robocomp:focal_dsr
    entrypoint: sh -c "(rcnode &) ; ls; cd components/idserver && cmake . && make -j4&& (./bin/idserver &) ; ls ; cd ../viriatoDSR/ && cmake . && make -j4 && (./bin/viriatoDSR)"
    environment: 
        - DISPLAY=$DISPLAY
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
    user: robolab
    ports:
        - 9999:9999
        - 9998:9998
